export const typeMap = {
  all: 'ทั้งหมด',
  metals: 'โลหะ',
  papers: 'กระดาษ',
  bottles: 'ขวด / ขวดพลาสติก',
  plastics: 'พลาสติก',
  coppers: 'ทองแดง',
  electronics: 'เครื่องใช้ไฟฟ้าเก่า',
  cans: 'กระป๋อง',
  zincs: 'สังกะสี',
  aluminum: 'อลูมิเนียม',
  stainless: 'สแตนเลส',
  crates: 'ลังเบียร์ / ลังเหล้า',
  another: 'อื่นๆ',
} as const
